version: '3.0'
services:
  postgres:
    container_name: e-commerce
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Pass2020!
    ports:
      - "5433:5432"
    volumes:
      - "${HOME}/postgres-data/:/var/lib/postgresql/data"
    networks:
      - e_commerce_network

  springboot-app:
    container_name: e-commerce
    image: ecommerce-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=qa
    depends_on:
      - postgres
    networks:
      - e_commerce_network

  networks:
    e_commerce_network:
      driver: bridge