spring:
  application:
    name: e-commerce

custom:
  postgres:
    host: localhost
    port: 5433
    database: postgres
    schema: ecommerce-prod
    username: postgres
    password: Pass2020!

server:
  port: 8081